<?php
/**
 * Mass Open — agenda plumbing. Run from the repository root.
 *
 *   php tools/agenda.php sync     _data/events.yml  ->  events table
 *   php tools/agenda.php export   accepted talks    ->  _data/agenda.yml
 *   php tools/agenda.php status   what is scheduled where
 *
 * Two one-way flows, so nothing is ever ambiguous about who owns what:
 *
 *   Events   are authored in git and pushed into the database, which only
 *            needs them so a talk can point at one.
 *   Agendas  are assembled in the database (review, accept, schedule) and
 *            pulled back into git for the static build.
 *
 * Only talks that are BOTH review_status='accepted' AND status='verified' are
 * exported, and only the fields meant to be public. Emails, IP addresses,
 * reviewer notes and rejected proposals never leave the database, so no bug in
 * a template can leak them.
 *
 * A talk booked for more than one event (cfp_schedule has a row per booking)
 * is exported under each of them, with that event's own running order.
 *
 * Reads the same MASSOPEN_DB_* environment variables as the site.
 */

declare(strict_types=1);

$root = dirname(__DIR__);
require $root . '/subscribe_lib.php';

$command = $argv[1] ?? 'help';

/** Minimal YAML emitter — quotes and escapes every scalar. */
function y(?string $v): string
{
    return '"' . str_replace(['\\', '"', "\n"], ['\\\\', '\\"', ' '], (string) $v) . '"';
}

/** Parse _data/events.yml without a YAML extension: the shape is known. */
function read_events(string $path): array
{
    $events  = [];
    $current = null;

    foreach (file($path, FILE_IGNORE_NEW_LINES) as $line) {
        if (preg_match('/^\s*#/', $line) || trim($line) === '') {
            continue;
        }
        if (preg_match('/^- (\w+):\s*(.*)$/', $line, $m)) {
            if ($current) { $events[] = $current; }
            $current = [$m[1] => trim($m[2], " \"'")];
        } elseif ($current !== null && preg_match('/^\s+(\w+):\s*(.*)$/', $line, $m)) {
            $current[$m[1]] = trim($m[2], " \"'");
        }
    }
    if ($current) { $events[] = $current; }

    return $events;
}

$pdo = mo_pdo();

switch ($command) {

/* ------------------------------------------------------------------------ */
case 'sync':
    $file = $root . '/_data/events.yml';
    $events = read_events($file);
    $n = 0;

    foreach ($events as $e) {
        if (empty($e['slug'])) {
            fwrite(STDERR, "  ! skipping an event with no slug: " . ($e['title'] ?? '?') . "\n");
            continue;
        }
        $stmt = $pdo->prepare(
            'INSERT INTO events (slug, title, starts_on, location)
                  VALUES (:slug, :title, :starts_on, :location)
             ON DUPLICATE KEY UPDATE
                  title = VALUES(title),
                  starts_on = VALUES(starts_on),
                  location = VALUES(location)'
        );
        $stmt->execute([
            ':slug'      => $e['slug'],
            ':title'     => $e['title'] ?? $e['slug'],
            ':starts_on' => $e['starts_on'] ?? null,
            ':location'  => $e['location'] ?? null,
        ]);
        $n++;
    }

    // Events removed from the file are left in place on purpose: deleting one
    // would cascade through cfp_schedule and unschedule its talks. Report
    // them instead.
    $slugs = array_column($events, 'slug');
    $stale = $pdo->query('SELECT slug FROM events')->fetchAll(PDO::FETCH_COLUMN);
    foreach (array_diff($stale, $slugs) as $gone) {
        fwrite(STDERR, "  ! '$gone' is in the database but not in events.yml (left alone)\n");
    }

    echo "Synced $n event(s) from _data/events.yml\n";
    break;

/* ------------------------------------------------------------------------ */
case 'export':
    // LEFT JOINs all the way down, so an event with nothing scheduled yet is
    // still listed and renders its "not announced" state rather than vanishing
    // from the index. A talk booked for two events comes back on both, each
    // time with that booking's own slot.
    $rows = $pdo->query(
        "SELECT e.slug AS event_slug, e.title AS event_title,
                e.starts_on, e.location,
                s.id, s.name, s.bio, s.topic, s.abstract, s.headshot, cs.slot_order
           FROM events e
           LEFT JOIN cfp_schedule cs
             ON cs.event_id = e.id
           LEFT JOIN cfp_submissions s
             ON s.id = cs.submission_id
            AND s.review_status = 'accepted'
            AND s.status = 'verified'
          ORDER BY e.starts_on, e.slug, cs.slot_order, s.id"
    )->fetchAll();

    $byEvent = [];
    foreach ($rows as $r) {
        $slug = $r['event_slug'];
        $byEvent[$slug]['event'] = $r;
        $byEvent[$slug]['talks'] ??= [];
        if ($r['id'] !== null) {
            $byEvent[$slug]['talks'][] = $r;
        }
    }

    $out  = "# GENERATED by tools/agenda.php export — do not edit by hand.\n";
    $out .= "# Accepted, verified talks only. Regenerate after changing the schedule.\n";
    $out .= '# Last export: ' . date('c') . "\n";

    if (!$byEvent) {
        $out .= "events: []\n";
    } else {
        $out .= "events:\n";
        foreach ($byEvent as $slug => $group) {
            $e = $group['event'];
            $out .= '  - slug: ' . y($slug) . "\n";
            $out .= '    title: ' . y($e['event_title']) . "\n";
            $out .= '    starts_on: ' . y($e['starts_on']) . "\n";
            $out .= '    location: ' . y($e['location']) . "\n";
            $out .= $group['talks'] ? "    talks:\n" : "    talks: []\n";
            foreach ($group['talks'] as $t) {
                // Slug from the topic, with the id appended so two talks with
                // similar titles cannot collide into one URL.
                $tslug = strtolower(preg_replace('/[^a-z0-9]+/i', '-', $t['topic']));
                $tslug = trim($tslug, '-');
                $tslug = ($tslug === '' ? 'talk' : substr($tslug, 0, 60)) . '-' . $t['id'];

                $out .= '      - slug: ' . y($tslug) . "\n";
                $out .= '        speaker: ' . y($t['name']) . "\n";
                $out .= '        bio: ' . y($t['bio']) . "\n";
                $out .= '        topic: ' . y($t['topic']) . "\n";
                $out .= '        abstract: ' . y($t['abstract']) . "\n";
                // Only when set. An empty value here would shadow the
                // convention lookup the template does on the speaker's name.
                if (($t['headshot'] ?? '') !== '') {
                    $out .= '        headshot: ' . y($t['headshot']) . "\n";
                }
                // Slot number, not the position in the list: a lone talk in
                // slot 4 must still show the 1pm start, not the first one.
                $out .= '        slot: ' . y((string) (int) $t['slot_order']) . "\n";
            }
        }
    }

    file_put_contents($root . '/_data/agenda.yml', $out);
    $talks = count(array_filter($rows, fn($r) => $r['id'] !== null));
    echo "Exported $talks talk(s) across " . count($byEvent) . " event(s) to _data/agenda.yml\n";
    echo "Rebuild the site to publish.\n";
    break;

/* ------------------------------------------------------------------------ */
case 'status':
    $rows = $pdo->query(
        "SELECT e.slug, e.starts_on, COUNT(s.id) AS talks
           FROM events e
           LEFT JOIN cfp_schedule cs ON cs.event_id = e.id
           LEFT JOIN cfp_submissions s
             ON s.id = cs.submission_id
            AND s.review_status = 'accepted' AND s.status = 'verified'
          GROUP BY e.id, e.slug, e.starts_on ORDER BY e.starts_on"
    )->fetchAll();
    foreach ($rows as $r) {
        printf("  %-14s %-12s %d accepted talk(s)\n", $r['slug'], $r['starts_on'] ?? '—', $r['talks']);
    }
    $un = (int) $pdo->query(
        "SELECT COUNT(*) FROM cfp_submissions s
          WHERE s.review_status='accepted' AND s.status='verified'
            AND NOT EXISTS (SELECT 1 FROM cfp_schedule cs WHERE cs.submission_id = s.id)"
    )->fetchColumn();
    if ($un > 0) {
        echo "  ! $un accepted talk(s) are not assigned to an event yet.\n";
    }

    // A talk on more than one bill is deliberate, but worth seeing at a glance.
    $repeat = $pdo->query(
        "SELECT s.topic, s.name, COUNT(*) AS bookings
           FROM cfp_submissions s
           JOIN cfp_schedule cs ON cs.submission_id = s.id
          WHERE s.review_status='accepted' AND s.status='verified'
          GROUP BY s.id, s.topic, s.name HAVING COUNT(*) > 1
          ORDER BY bookings DESC, s.id"
    )->fetchAll();
    foreach ($repeat as $r) {
        printf("  · %s (%s) is on %d bills\n", $r['topic'], $r['name'], (int) $r['bookings']);
    }
    break;

/* ------------------------------------------------------------------------ */
default:
    echo "usage: php tools/agenda.php sync|export|status\n";
    exit($command === 'help' ? 0 : 1);
}
